CREATE TABLE [User](
[Id] INT NOT NULL IDENTITY(1, 1),
[Name] NVARCHAR(80) NOT NULL,
[Email] VARCHAR(200) NOT NULL,
[Password] VARCHAR(255) NOT NULL,

CONSTRAINT [PK_User] PRIMARY KEY([Id]),
CONSTRAINT [UQ_User_Email] UNIQUE([Email]),
)
CREATE NONCLUSTERED INDEX [IX_User_Email] ON [User]([Email])

CREATE TABLE [Tag] (
[Id] INT NOT NULL IDENTITY(1, 1),
[Name] VARCHAR(80) NOT NULL,
[UserId] INT NOT NULL,

CONSTRAINT [PK_Tag] PRIMARY KEY([Id]),
CONSTRAINT [FK_Tag_User] FOREIGN KEY([UserId]) REFERENCES [User]([Id]),

)

CREATE TABLE [Task](
[Id] INT NOT NULL IDENTITY(1, 1),
[Name] NVARCHAR(80) NOT NULL,
[Description] VARCHAR(200) NOT NULL,
[Status] NVARCHAR(80) NOT NULL,
[TagId] INT NOT NULL,
[UserId] INT NOT NULL,

CONSTRAINT [PK_Task] PRIMARY KEY([Id]),
CONSTRAINT [FK_Task_Tag] FOREIGN KEY([TagId]) REFERENCES [Tag]([Id]),
CONSTRAINT [FK_Task_User] FOREIGN KEY([UserId]) REFERENCES [User]([Id]),
)